classDiagram
   
   ImageCapture --> CameraInterface
    Config --> ImageCapture
   Config <-- CameraConfig
   CameraInterface --> EvaluationSystem
   EvaluationSystem --> AlarmSystem

   namespace Camera {
    class ImageCapture {
        -timer: Timer
        -geolocation: GeoLocation
        -time: TimeStamp

            +take_picture() Image
            +post_image(image: Image) void
            +get_time() TimeStamp
            +get_geolocation() GeoLocation
        }

        class Config {
            -resolution: Array[width, height]
            -is_color: bool
            -interval: int
            -night_vision: bool

            +get_resolution() Array[width, height]
            +get_color() bool
            +get_interval() int
            +get_night_vision() bool
        }
    }

    namespace System {
        class CameraInterface {
            +receive_post(image: Image) void
            -send_to_processor(image: Image) void
        }

        class CameraConfig {
            -resolution: Array[width, height]
            -is_color: bool
            -interval: int
            -night_vision: bool

            +update_resolution(resolution: Array[int, int]) void
            +update_interval(interval: int) void
            +set_color(is_color: bool) void
            +set_night_vision(night_vision: bool) void
        }

        class EvaluationSystem {
            +get_image() Image
            +evaluate_image(image: Image) void
            +send_alarm(severity: int, location: GeoLocation, time: TimeStamp)

        }

        class AlarmSystem {
            +recieve_alarm(severity: int, location: GeoLocation, time: TimeStamp)
            +broadcast_alarm(severity: int, location: GeoLocation, time: TimeStamp)
        }
    }
